name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      - name: Install Backend Dependencies
        run: npm install

      - name: Build Backend
        run: npm run build --if-present

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build --if-present
